### ISSUE TITLE
Twitter command should handle usernames with or without @

### ISSUE THREAD

**Issue by ErikBoesen** [ErikBoesen/Yalebot#27]

**Comment by victor-hugo-dc** [comment]
You could probably just cut out:
```     
if '@' not in query:
            return 'Incorrect format, be sure to use the @ symbol'
```
and change the url variable but keep the ',' if statement because that determines whether a message is added to the DM link.
```
        if ',' in query:
            qlist = query.split(',', 1)
            query = qlist[0].strip()
            msg = qlist[1].strip()
        url = 'http://gettwitterid.com/?user_name={user}&submit=GET+USER+ID'.format(user=query)
```
I prefer using BeautifulSoup for this module but if you prefer using the Twitter API, this repo utilizes it: https://github.com/ideoforms/python-twitter-examples/blob/master/twitter-search.py

**Comment by ErikBoesen** [comment]
Want to make a PR to fix the @ issue? I would probably just use `lstrip` to remove the `@`. 

I don't mind using BeautifulSoup much. It's a little clunky, but Twitter's API user verification process is a pain anyway.
